steps:

- id: "Executando imagem docker"
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
  args: ['-f', 'docker-compose.yml', 'up', '-d'] 
  
- id: "Verifica se os containers estão rodando"
  name: 'gcr.io/cloud-builders/docker'
  args: ['ps']


- id: "Instalando as dependências com o composer"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app-laravel', 'composer', 'install']

- id: "Copiar o arquivo .env.example para .env"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app-laravel', 'cp', '.env.example', '.env']

- id: "Rodar um artisan key:generate"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app-laravel', 'php', '/var/www/artisan', 'key:generate']

- id: "Executar as migrações"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app-laravel', 'php', '/var/www/artisan', 'migrate']

- id: "Executar os testes utilizando o PHPUnit"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app-laravel', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']